FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
COPY ./input_xlsx /code/input_xlsx
COPY ./script /code/script
COPY ./static /code/static
COPY ./templates /code/templates
COPY ./config.py /code/config.py
 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
# CMD ["uvicorn", "app.main_api:app", "--host", "0.0.0.0", "--port", "8001"]